# fly.toml app configuration file generated for youchannel-service on 2026-01-01T11:11:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'youchannel-service'
primary_region = 'iad'

[build]
  [build.args]
    VITE_SUPABASE_URL = "https://wzbiqlxovmxlatrgxzgc.supabase.co"
    VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6YmlxbHhvdm14bGF0cmd4emdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5OTE4OTQsImV4cCI6MjA4MjU2Nzg5NH0.SdGOKw9iHdOP_cHU9XcJF4klEhs-oc_-2w61b_ooEU0"


[env]
  PORT = "4000"
  NODE_ENV = "production"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
